added categories tests
alkemyTech/OT224-server pull request #124
Opened 2022-07-08 21:13 UTC by SLRonzoni

added categories tests

[https://github.com/alkemyTech/OT224-server/tree/OT224-121](url)

2022-07-11 12:44 UTC, ateszki commented on tests/categories.test.js
> +
el before por fuera del describe funciona? esto no lo sabia

2022-07-11 12:47 UTC, SLRonzoni commented
Si, funciona perfecto, los test de categorías y testimonial, lo tienen así
y corren bien

El lun., 11 jul. 2022 09:44, ateszki ***@***.***> escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/categories.test.js
> <https://github.com/alkemyTech/OT224-server/pull/124#discussion_r917886585>
> :
>
> > +before( async function () {
> +  const responseAdmin = await request
> +  .post("/api/auth/login")
> +  .send({
> +    'email': ***@***.***',
> +    'password': '1234test',
> +  });
> +  adminToken = responseAdmin.body.token;
> +
> +  const responseRegular = await request
> +  .post("/api/auth/login")
> +  .send({
> +    'email': ***@***.***',
> +    'password': '1234test',
> +  });
> +  regularToken = responseRegular.body.token;
> +});
> +
>
> el before por fuera del describe funciona? esto no lo sabia
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT224-server/pull/124#pullrequestreview-1034274701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASP5EEYDBYQHH3Q6XVSCZB3VTQJMVANCNFSM53CFGNBA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-11 12:47 UTC, ateszki requested changes
Deberias agregar un metodo after que elimine todo lo que creas con los tests. utilizar algo en los nombres de las categorias que te permita identificar las que se crearon mediante test y eliminarlas.

2022-07-11 12:47 UTC, ateszki commented on tests/categories.test.js
> +  });
Para todos los test de update y delete que usan id, lo mejor es usar los que creas con el test de creacion. porque si no cuando la base de datos vaya creciendo estos test van a fallar o van a borrar cosas que no deberian.

2022-07-12 23:12 UTC, ateszki requested changes

2022-07-12 23:12 UTC, ateszki commented on tests/categories.test.js
> +    .set("Authorization", `Bearer ${adminToken}`)
fijate de usar tu id de test, porque si por algun motivo llega a borrar podes terminar borrando datos en produccion

2022-07-13 14:46 UTC, ateszki approved these changes

2022-07-13 14:46 UTC, merged