mejoras modelo de usuario
alkemyTech/OT224-server pull request #14
Opened 2022-06-16 21:10 UTC by hugotata78

Se agregaron metodos allowNull: false a las propiedades firtName, lastName, email y password, como así también metodo unique al email

2022-06-16 22:24 UTC, ateszki requested changes

2022-06-16 22:24 UTC, ateszki commented on migrations/20200921211634-create-user.js
>          type: Sequelize.STRING
fijate que en el ticket el campo se llama photo, cambiale el nombre de image a photo por favor

2022-06-17 15:57 UTC, hugotata78 commented on migrations/20200921211634-create-user.js
>          type: Sequelize.STRING
Ok Andres ahí lo cambio

2022-06-20 00:15 UTC, ateszki approved these changes

2022-06-20 00:15 UTC, merged