Ot224 145 - Normalize organizations
alkemyTech/OT224-server pull request #158
Opened 2022-07-18 01:14 UTC by cesarpo777

- Apliqué el base controller a organization.controller.js
- Modifiqué las importaciones de los middlewares y los validators en organization.route.js
- Apliqué el router.use para rutas que tienen en común un middleware
- Apliqué el middleware de idExists en las rutas de organizations que lo requerían
- Creé el archivo de documentación de organization
- Cambié la estructura de los test de organization

2022-07-18 21:51 UTC, ateszki requested changes

2022-07-18 21:51 UTC, ateszki commented on controllers/organization.controller.js
> +    let data = {
data deberia ser una constante, no le vas a reasignar valor.

2022-07-19 11:49 UTC, cesarpo777 commented on controllers/organization.controller.js
> +    const data = req.body;
Aca no lo desesctructure porque no se que campo le va a editar. Y en la ruta no tiene ningun validador

2022-07-19 14:28 UTC, ateszki approved these changes

2022-07-19 14:28 UTC, merged