Ot224 21
alkemyTech/OT224-server pull request #16
Opened 2022-06-17 16:23 UTC by FlorenciaAGarrido

@ateszki  En este pull request esta el modelo, controller y router de activity.

2022-06-20 00:22 UTC, ateszki requested changes

2022-06-20 00:22 UTC, ateszki commented on controllers/activities.js
> +    next(err);
No devuelvas el next aca ni en los otros, por ahora tiraremos error 500 con el error `res.status(500).send(error)` correjilo en todos los metodos por favor

2022-06-20 00:22 UTC, ateszki commented on models/activity.js
> +    deletedAt: DataTypes.DATE
por favor saca deletedAt de aca

2022-06-20 00:22 UTC, ateszki commented on models/activity.js
> +    modelName: 'Activity',
por favor agrega paranoid: true aca https://sequelize.org/docs/v6/core-concepts/paranoid/

2022-06-20 00:22 UTC, ateszki commented on seeders/20220616232349-demo-activity.js
> +};
Este archivo esta fuera del scope del ticket, de momento lo dejamos, pero es importante atenerse al scope solicitado

2022-06-20 22:18 UTC, FlorenciaAGarrido commented
Hola @ateszki,  envié correcciones.

2022-06-21 11:37 UTC, ateszki approved these changes

2022-06-21 11:37 UTC, merged