feat(OT224-141):Normalize Endpoints Comments
alkemyTech/OT224-server pull request #165
Opened 2022-07-19 12:36 UTC by FlorenciaAGarrido

@ateszki  Envio endpoints de comentarios normalizados.

2022-07-19 14:35 UTC, ateszki requested changes

2022-07-19 14:35 UTC, ateszki commented on documentation/swagger.js
> +require('dotenv').config()
este no deberia hacer falta aca

2022-07-19 14:39 UTC, ateszki commented on documentation/swagger.js
> +require('dotenv').config()
antes de corregir hacete un pull de esta rama que resolvi los conflictos y tu copia local debe estar desactualizada

2022-07-20 12:15 UTC, FlorenciaAGarrido commented
@ateszki  Envíe correcciones.

2022-07-20 14:08 UTC, ateszki approved these changes

2022-07-20 14:08 UTC, merged