Ott224 22
alkemyTech/OT224-server pull request #2
Opened 2022-06-15 17:46 UTC by ChristianLeiva

Crear modelo, migración y controlador base de Members

2022-06-15 21:07 UTC, ateszki commented
@ChristianLeiva fijate que faltaria el controlador

2022-06-15 22:38 UTC, ateszki requested changes

2022-06-15 22:38 UTC, ateszki commented on controllers/users.controllers.js
> +}
Por favor arma una carpeta para los middlewares y pone esta funcion en su propio archivo luego importala aqui

2022-06-15 22:38 UTC, ateszki commented on routes/users.js
> +router.get('/verify', userController.verifyIsAdmin)
Para que seria este endpoint?

2022-06-16 00:14 UTC, ChristianLeiva commented on controllers/users.controllers.js
> +}
Ya lo movi a una carpeta nueva.

2022-06-16 00:18 UTC, ChristianLeiva commented on routes/users.js
> +router.get('/verify', userController.verifyIsAdmin)
ese se me paso, era para probar el middleware.

Con respecto al middleware para verificar si el usuario es admin o no, tengo la duda de donde tengo que tomar el objeto usuario, lo primero que se me ocurrió es tomarlo del request.header que trae el token, pero como entiendo que todavía no esta hecho, lo  tomo de la base de datos.

¿O de donde debería tomarlo?

2022-06-16 12:47 UTC, ateszki requested changes

2022-06-16 12:47 UTC, ateszki commented on controllers/members.controller.js
> +        members.length === 0 ? (res.send("Empty database")) : (res.send(members))
Aca devolve directamente memebers, si esta vacio que vuelva vacio.

2022-06-16 12:47 UTC, ateszki commented on controllers/users.controllers.js
> +    const users =  await ModeloUser.findAll()
este hacelo consistente con el de members. metele el try catch

2022-06-16 12:47 UTC, ateszki commented on models/member.js
> +    sequelize,
Aca agrega `paranoid: true` para los soft deletes ver doc https://sequelize.org/docs/v6/core-concepts/paranoid/

2022-06-16 12:47 UTC, ateszki commented on middelwares/user.middelware.js
> +    const userData =  await ModeloUser.findOne({where: {firstname: req.body.firstname}})
El user te va a venir luego en el request, por ahora lo dejamos asi.

2022-06-16 15:14 UTC, merged