Ot224 30
alkemyTech/OT224-server pull request #20
Opened 2022-06-18 14:08 UTC by SLRonzoni

added welcome email view and styles
( folders views and public )

[https://github.com/alkemyTech/OT224-server/tree/ot224-30](url)

2022-06-20 00:37 UTC, ateszki requested changes

2022-06-20 00:37 UTC, ateszki commented on public/styleEmail.css
> +      /* mso-table-lspace: 0pt;
No usaria hoja de estilos para un template de emails. los clientes de email muchas veces ignoran las hor=jas de estilo, utilizaria estilos directo en las etiquetas html como hiciste con el background color. no usaria media queries aca y simplificaria mucho el css

2022-06-20 00:37 UTC, ateszki commented on views/emailWelcome.ejs
> +                                width="312"> -->
porque la dejaste comentada???

2022-06-20 00:37 UTC, ateszki commented on views/emailWelcome.ejs
> +                            <span style="text-align: left;"> 👉 Facebook  : Somos_Mas</span> <br></br>
+1 por usar emojis, me copan!

2022-06-20 00:53 UTC, SLRonzoni commented
La imagen del logo Alkemy está comentada porque sabía que iba el logo de la
ONG pero no encontré el link para ponerlo.

Modifico todo lo indicado y vuelvo a hacer commit

El dom., 19 jun. 2022 21:37, ateszki ***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In public/styleEmail.css
> <https://github.com/alkemyTech/OT224-server/pull/20#discussion_r901181035>
> :
>
> > +
>
> ***@***.*** url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);
>
> ***@***.*** url(https://fonts.googleapis.com/css?family=Cabin:400,700);
>
> +
>
> +    #outlook a {
>
> +      padding: 0;
>
> +    }
>
> +
>
> +    .ReadMsgBody {
>
> +      width: 100%;
>
> +    }
>
> +
>
> +    .ExternalClass {
>
> +      width: 100%;
>
> +    }
>
> +
>
> +    .ExternalClass * {
>
> +      line-height: 100%;
>
> +    }
>
> +
>
> +    body {
>
> +      margin: 0;
>
> +      padding: 0;
>
> +      -webkit-text-size-adjust: 100%;
>
> +      -ms-text-size-adjust: 100%;
>
> +    }
>
> +
>
> +    table,
>
> +    td {
>
> +      border-collapse: collapse;
>
> +      /* mso-table-lspace: 0pt;
>
>
> No usaria hoja de estilos para un template de emails. los clientes de
> email muchas veces ignoran las hor=jas de estilo, utilizaria estilos
> directo en las etiquetas html como hiciste con el background color. no
> usaria media queries aca y simplificaria mucho el css
> ------------------------------
>
> In views/emailWelcome.ejs
> <https://github.com/alkemyTech/OT224-server/pull/20#discussion_r901181160>
> :
>
> > +                              <!--              AQUI IRIA EL LOGO DE LA ONG, LA IMAGEN QUE ESTA DEBAJO ES EL LOGO DE ALKEMY
>
> +                                <img height="auto"
>
> +                                src="https://s3-eu-west-1.amazonaws.com/topolio/uploads/6082338c1a7ee/1619145692.jpg"
>
> +                                style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
>
> +                                width="312"> -->
>
>
> porque la dejaste comentada???
> ------------------------------
>
> In views/emailWelcome.ejs
> <https://github.com/alkemyTech/OT224-server/pull/20#discussion_r901181251>
> :
>
> > +                            <span style="text-align: left;"> 👉 Email     : ***@***.***</span><br></br>
>
> +                            <span style="text-align: left;"> 👉 Teléfono  : 11-6011-2988</span> <br></br>
>
> +                            <span style="text-align: left;"> 👉 Instagram : SomosMas </span> <br></br>
>
> +                            <span style="text-align: left;"> 👉 Facebook  : Somos_Mas</span> <br></br>
>
>
> +1 por usar emojis, me copan!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT224-server/pull/20#pullrequestreview-1011591080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASP5EE6ODXAWQBIGFJLNLUDVP64NRANCNFSM5ZEZ7MGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-21 18:23 UTC, ateszki commented
lo seguimos en este https://github.com/alkemyTech/OT224-server/pull/21

2022-06-21 18:23 UTC, closed without merging