modelo y migraciones de contactos
alkemyTech/OT224-server pull request #37
Opened 2022-06-22 14:40 UTC by hugotata78

modelo y migraciones de contactos contienen campo name,phone, email, message y deleteAt. Los campos name e email son requeridos

2022-06-22 15:36 UTC, hugotata78 commented
No olvidar ejecutar el comando npx sequelize-cli db:migrate para migrar el modelo a la db

2022-06-22 15:59 UTC, hugotata78 commented
Agregue un seeders para guardar algunos contactos en la db. Ejecutar comando npx sequelize-cli db:seed:all para guardar esos contactos

2022-06-22 22:29 UTC, ateszki requested changes

2022-06-22 22:29 UTC, ateszki commented on seeders/20220622154335-create-demo-contacts.js
> +      deletedAt: new Date(),
si le pones fecha a deletedAt no los vas a poder usar. mandale null ahi o no popules ese campo en el seeder

2022-06-22 23:06 UTC, hugotata78 commented on models/contacts.js
> +    deletedAt: DataTypes.DATE
No entiendo el cambio de sacar el deletedAt. 
Lo puse porque lo piden en el ticket de jira

2022-06-22 23:13 UTC, hugotata78 commented on seeders/20220622154335-create-demo-contacts.js
> +      deletedAt: new Date(),
Ok lo saco del seeders

2022-06-22 23:35 UTC, hugotata78 commented
Cambios realizados en modelo contacts y seeders

2022-06-23 00:32 UTC, ateszki commented on models/contacts.js
> +    deletedAt: DataTypes.DATE
el deletedat tenelo en la migracion pero no hace falta que lo pongas en el modelo, funciona igual que createdAt y updatedAt, lo maneja sequelize.

2022-06-23 00:33 UTC, ateszki approved these changes

2022-06-23 00:33 UTC, merged