Se creo la lógica para obtener todos los testimonials y se creó el e…
alkemyTech/OT224-server pull request #47
Opened 2022-06-23 15:13 UTC by Kevjos

- Se creó el endpoint para actualizar un testimonial por id.
- Se hizo un cambio para poder validar el token del usuario logueado en el user.middelware.

2022-06-23 21:32 UTC, ateszki requested changes

2022-06-23 21:32 UTC, ateszki commented on controllers/testimonial.controller.js
> +    }
Aca no devuelvas el 404, porque no hay un id, la ruta sigue siendo valida, lo que pasa es que va a devolver un recorset vacio.

devolve siempre `res.status(200).send(testimonials);`

2022-06-23 21:32 UTC, ateszki commented on controllers/testimonial.controller.js
> +            res.status(404).send({message: "Testimonial no found!"});
Aca si es correcto el 404 porque la ruta tiene un id.

2022-06-23 21:55 UTC, Kevjos commented on controllers/testimonial.controller.js
> +    }
Hecho

2022-06-23 22:13 UTC, ateszki requested changes

2022-06-23 22:13 UTC, ateszki commented on controllers/testimonial.controller.js
> +        }
no hace falta el if si en ambos casos devolves lo mismo, lo que intentaba decirte es que solo devuelvas 
`res.status(200).send(testimonials);` sin el if el else o nada de eso

2022-06-24 11:42 UTC, ateszki approved these changes

2022-06-24 11:42 UTC, merged