Ot224 110
alkemyTech/OT224-server pull request #66
Opened 2022-06-27 17:00 UTC by hugotata78

Se agregó validación al archivo contactsValidator.js para cotejar que el email de los contactos sea único al momento de cargarse los contactos, como así también la propiedad unique:true al modelo contacts

2022-06-27 17:16 UTC, hugotata78 commented
Se modificó las validaciones del email de forma similar a lo hecho en las validaciones de email del usuario para que devuelva el error exacto que se produce al intentar introducir el mismo.

2022-06-27 18:12 UTC, ateszki requested changes

2022-06-28 13:29 UTC, ateszki requested changes

2022-06-28 13:29 UTC, ateszki commented on migrations/20220622143321-create-contacts.js
> +        unique:true
@hugotata78 por favor des hace estos cambios, este archivo no debe modificarse en este pr

2022-06-28 13:29 UTC, ateszki commented on migrations/20220627204535-create-some-contacts.js
> +      },
esta es la unica columna que deberias definir en esta migracion y usar el comando `queryInterface.changeColumn` en vez de el `queryInterface.createTable`

2022-06-28 16:23 UTC, hugotata78 commented
@ateszki yo probé los cambios en mi repo local, se genera la nueva migración pero no impacta el cambio en la propiedad mail, subi los cambios igualmente para que los veas a ver si me podes dar una mano para encontrarle la vuelta. No me arroja ningún error en consola pero como te dije no se reflejan los cambios en el atributo unique de la propiedad email.

2022-06-29 01:13 UTC, ateszki commented
@hugotata78 la migracion esta bien, da error porque en el seeder de contactos creaste dos contactos con el mismo email. modifica el seeder y regenera toda la db

2022-06-29 12:45 UTC, merged