added paginated to categories get all
alkemyTech/OT224-server pull request #98
Opened 2022-07-04 18:26 UTC by SLRonzoni

added paginated to categories get all

[https://github.com/alkemyTech/OT224-server/tree/OT224-85](url)

2022-07-04 20:05 UTC, ateszki requested changes

2022-07-04 20:05 UTC, ateszki commented on controllers/categories.controller.js
> +     const showNames=categoriesPaginated.data.map((element=>{return element.name}))
hardcodear la url es incorrecto aca, y no deberiamos pasar esta url no le des bola al ticket que esta impreciso. con el helper de paginacion ya vuelven la pagina anterior y la siguiente y con eso se completa el requerimiento. tampoco entiendo bien que estas haciendo con esa variable showNames.

2022-07-04 20:11 UTC, SLRonzoni commented
ShowNames, la uso para mostrar solo los nombres  de las categorías ( que es
lo que pide mí ticket de listado de categorias ), porque el helper devuelve
un array

Corrijo lo de la URL.



El lun., 4 jul. 2022 17:05, ateszki ***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In controllers/categories.controller.js
> <https://github.com/alkemyTech/OT224-server/pull/98#discussion_r913250168>
> :
>
> > +     const previous=categoriesPaginated.previousPage===null ? '' : `http://localhost:3000/api/categories?page=${categoriesPaginated.previousPage}` <http://localhost:3000/api/categories?page=$%7BcategoriesPaginated.previousPage%7D>
> +     const next=categoriesPaginated.nextPage===null ? '' : `http://localhost:3000/api/categories?page=${categoriesPaginated.nextPage}` <http://localhost:3000/api/categories?page=$%7BcategoriesPaginated.nextPage%7D>
> +
> +     const showNames=categoriesPaginated.data.map((element=>{return element.name}))
>
> hardcodear la url es incorrecto aca, y no deberiamos pasar esta url no le
> des bola al ticket que esta impreciso. con el helper de paginacion ya
> vuelven la pagina anterior y la siguiente y con eso se completa el
> requerimiento. tampoco entiendo bien que estas haciendo con esa variable
> showNames.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT224-server/pull/98#pullrequestreview-1027877747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASP5EE2ILBHGVVIGYSRG4JTVSM7ZFANCNFSM52T5PQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-05 12:59 UTC, ateszki approved these changes

2022-07-05 12:59 UTC, merged